export const DATA_SAMPLE = "DATA_SAMPLE";
export const LOADING = "LOADING";
export const STOP_LOADING = "STOP_LOADING";
export const EXPERIMENT_COMPLETED = "EXPERIMENT_COMPLETED";
export const START_PREDICTION = "START_PREDICTION";